name: Generate ASCII artwork

on: push

jobs: 
    First-job:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout Repo
       uses: actions/checkout@v6

     - name: Install cowsay program
       run : sudo apt-get install cowsay -y

     - name: Execute cowsay CMD
       run: cowsay -f dragon "Run for cover, I am a Dragon ... RAWR" >> dragon.txt

     - name: Test files exists
       run: grep -i dragon "dragon.txt"

     - name: Read files
       run: cat dragon.txt    
       
     - name: List repo files
       run: ls -ltra
     
#   - name: Read file
#    run : cat README.md