name: Generate ASCII artwork

on: push

jobs: 
    First-job:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout Repo
       uses: actions/checkout@v6

     - name: List repo files
       run: ls -ltra
       
     - name: Executing shell script
       run: ./ascii-scropt.sh  
       
     
#   - name: Read file
#    run : cat README.md