name: Exploring variable and secrets

on: push

env:
  CONTAINER_REGISTRY: Docker.io
  IMAGENAME: my-nginx-latest

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: build docker
          run: echo docker build -t $CONTAINER_REGISTRY/${{ vars. DOCKER_USERNAME }}/$IMAGENAME:latest
         
        - name: Docker login
          run: echo docker login --username=$DOCKER_USERNAME --password=${{ secrets.DOCKER_PASSWORD}}

        - name: Docker push
          run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGENAME:latest

    deploy:
        runs-on: ubuntu-latest
        steps: 
        - name: Docker run
          run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGENAME:latest