name: Exploring variable and secrets

on: push

env:
  CONTAINER_REGISTRY: Docker.io
  DOCKER_USERNAME: Shameer
  IMAGENAME: my-nginx-latest
  DOCKER_PASSWORD: shameer12334

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: build docker
          run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGENAME:latest
         
        - name: Docker login
          run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

        - name: Docker push
          run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGENAME:latest

    deploy:
        runs-on: ubuntu-latest
        steps: 
        - name: Docker run
          run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGENAME:latest